using System.Globalization;
using System.Numerics;
using System.Text;

namespace TREditorSharp.IO;

/// <summary>
/// Writes a <see cref="SpatialMesh"/> as Wavefront OBJ
/// </summary>
public sealed class ObjMeshWriter
{
    private const string FloatFormat = "G9";

    /// <inheritdoc />
    public string FileExtension => "obj";

    /// <inheritdoc />
    public void Write(SpatialMesh mesh, Stream destination, MeshWriterOptions? options = null)
    {
        ArgumentNullException.ThrowIfNull(mesh);
        ArgumentNullException.ThrowIfNull(destination);

        var opts = options ?? new MeshWriterOptions();

        var leaveOpen = opts.LeaveStreamOpen;
        using var writer = new StreamWriter(
            destination,
            new UTF8Encoding(encoderShouldEmitUTF8Identifier: false),
            bufferSize: 65_536,
            leaveOpen: leaveOpen
        );

        writer.WriteLine("# Wavefront OBJ file generated by TREditor");

        var verts = mesh.Vertices;
        var faces = mesh.Faces;
        var positions = verts.GetNativeColumn<Vector3, VertexPositionTag>();

        int n = verts.LiveCount;
        if (n == 0)
            return;

        var byDense = new Vector3[n];
        foreach (var v in verts.Live)
        {
            int d = verts.GetDenseIndex(v);
            byDense[d] = positions[d];
        }

        // Fix output format to use expected ASCII period for floating point serialization.
        var inv = CultureInfo.InvariantCulture;

        for (int i = 0; i < n; i++)
        {
            var p = byDense[i];
            writer.Write('v');
            writer.Write(' ');
            writer.Write(p.X.ToString(FloatFormat, inv));
            writer.Write(' ');
            writer.Write(p.Y.ToString(FloatFormat, inv));
            writer.Write(' ');
            writer.WriteLine(p.Z.ToString(FloatFormat, inv));
        }

        var triScratch = new List<int>(256);
        var cornerScratch = new List<int>(64);

        foreach (var face in faces.Live)
        {
            if (mesh.Faces[face].FirstHalfEdge.IsNull)
                continue;

            if (opts.TriangulateFaces)
            {
                triScratch.Clear();
                if (!mesh.TriangulateFace(face, triScratch))
                    continue;

                for (int t = 0; t + 2 < triScratch.Count; t += 3)
                {
                    WriteFaceLine(writer, triScratch[t], triScratch[t + 1], triScratch[t + 2], inv);
                }
            }
            else
            {
                cornerScratch.Clear();
                foreach (var he in mesh.HalfEdgesAroundFace(face))
                {
                    ref var halfEdge = ref mesh.HalfEdges.GetUnsafeRef<HalfEdge, HalfEdge>(he);
                    cornerScratch.Add(verts.GetDenseIndex(halfEdge.Origin));
                }

                if (cornerScratch.Count < 3)
                    continue;

                WriteFaceLine(writer, cornerScratch, inv);
            }
        }
    }

    private static void WriteFaceLine(
        StreamWriter writer,
        int d0,
        int d1,
        int d2,
        IFormatProvider inv
    )
    {
        writer.Write('f');
        writer.Write(' ');
        writer.Write((d0 + 1).ToString(inv));
        writer.Write(' ');
        writer.Write((d1 + 1).ToString(inv));
        writer.Write(' ');
        writer.WriteLine((d2 + 1).ToString(inv));
    }

    private static void WriteFaceLine(
        StreamWriter writer,
        List<int> denseCorners,
        IFormatProvider inv
    )
    {
        writer.Write('f');
        for (int i = 0; i < denseCorners.Count; i++)
        {
            writer.Write(' ');
            writer.Write((denseCorners[i] + 1).ToString(inv));
        }

        writer.WriteLine();
    }
}
